[package]
name = "sml-rs"
version = "0.0.1"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
description = "Smart Message Language (SML) parser written in Rust"
repository = "https://github.com/fkohlgrueber/sml-rs"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
alloc = []

[dependencies]
crc = "3.0.0"

[dev-dependencies]
hex-literal = "0.3.4"
