[package]
name = "sml-rs-macros"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true
path = "sml-rs-macros.rs"

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
